# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frame.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2100, 1214)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 2050, 871))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.show_data_groupbox = QtWidgets.QGroupBox(self.groupBox)
        self.show_data_groupbox.setGeometry(QtCore.QRect(30, 20, 1700, 701))
        self.show_data_groupbox.setObjectName("show_data_groupbox")
        self.tableWidget = QtWidgets.QTableWidget(self.show_data_groupbox)
        self.tableWidget.setGeometry(QtCore.QRect(60, 30, 1580, 661))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.result_groupbox = QtWidgets.QGroupBox(self.groupBox)
        self.result_groupbox.setGeometry(QtCore.QRect(1750, 20, 280, 701))
        self.result_groupbox.setObjectName("result_groupbox")
        self.score_label = QtWidgets.QLabel(self.result_groupbox)
        self.score_label.setGeometry(QtCore.QRect(20, 130, 81, 18))
        self.score_label.setObjectName("score_label")
        self.score = QtWidgets.QLabel(self.result_groupbox)
        self.score.setGeometry(QtCore.QRect(110, 130, 81, 18))
        self.score.setObjectName("score")
        self.level_label = QtWidgets.QLabel(self.result_groupbox)
        self.level_label.setGeometry(QtCore.QRect(20, 200, 81, 18))
        self.level_label.setObjectName("level_label")
        self.level = QtWidgets.QLabel(self.result_groupbox)
        self.level.setGeometry(QtCore.QRect(110, 200, 81, 18))
        self.level.setObjectName("level")
        self.real_score = QtWidgets.QLabel(self.result_groupbox)
        self.real_score.setGeometry(QtCore.QRect(20, 270, 81, 18))
        self.real_score.setObjectName("real_score")
        self.realscore = QtWidgets.QLabel(self.result_groupbox)
        self.realscore.setGeometry(QtCore.QRect(110, 270, 81, 18))
        self.realscore.setText("")
        self.realscore.setObjectName("realscore")
        self.real_level = QtWidgets.QLabel(self.result_groupbox)
        self.real_level.setGeometry(QtCore.QRect(20, 340, 81, 18))
        self.real_level.setObjectName("real_level")
        self.reallevel = QtWidgets.QLabel(self.result_groupbox)
        self.reallevel.setGeometry(QtCore.QRect(110, 340, 81, 18))
        self.reallevel.setObjectName("reallevel")
        self.select_file_button = QtWidgets.QPushButton(self.groupBox)
        self.select_file_button.setGeometry(QtCore.QRect(150, 760, 112, 34))
        self.select_file_button.setObjectName("select_file_button")
        self.show_data_button = QtWidgets.QPushButton(self.groupBox)
        self.show_data_button.setGeometry(QtCore.QRect(240, 820, 112, 34))
        self.show_data_button.setObjectName("show_data_button")
        self.predict_data_button = QtWidgets.QPushButton(self.groupBox)
        self.predict_data_button.setGeometry(QtCore.QRect(660, 820, 112, 34))
        self.predict_data_button.setObjectName("predict_data_button")
        self.close_button = QtWidgets.QPushButton(self.groupBox)
        self.close_button.setGeometry(QtCore.QRect(990, 820, 112, 34))
        self.close_button.setObjectName("close_button")
        self.file_path_label = QtWidgets.QLabel(self.groupBox)
        self.file_path_label.setGeometry(QtCore.QRect(340, 770, 841, 18))
        self.file_path_label.setObjectName("file_path_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1779, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "情报人员时效性评估"))
        self.show_data_groupbox.setTitle(_translate("MainWindow", "数据展示"))
        self.result_groupbox.setTitle(_translate("MainWindow", "结果与分析"))
        self.score_label.setText(_translate("MainWindow", "预测分数："))
        self.score.setText(_translate("MainWindow", ""))
        self.level_label.setText(_translate("MainWindow", "预测等级："))
        self.level.setText(_translate("MainWindow", ""))
        self.real_score.setText(_translate("MainWindow", "实际分数："))
        self.real_level.setText(_translate("MainWindow", "实际等级："))
        self.reallevel.setText(_translate("MainWindow", ""))
        self.select_file_button.setText(_translate("MainWindow", "选择文件"))
        self.show_data_button.setText(_translate("MainWindow", "数据展示"))
        self.predict_data_button.setText(_translate("MainWindow", "预测"))
        self.close_button.setText(_translate("MainWindow", "退出"))
        self.file_path_label.setText(_translate("MainWindow", ""))

